modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "strange_mod"
version = "Alpha 1.2.1"
displayName = "Strange Mod"
logoFile = "strange_mod.png"
authors = "StrangeDevs (adasdead & Slieko)"
description = '''
A very strange mod. I'm serious!
'''

[[dependencies.strange_mod]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"